CREATE TABLE PAYMENTS_DEFAULT (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    AMOUNT DECIMAL(18, 2) NOT NULL,
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PAYMENTS_FALLBACK (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    AMOUNT DECIMAL(18, 2) NOT NULL,
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);