version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" 
      - "8222:8222"
    command: [
      "-m", "8222"
    ]
    deploy:
      resources:
        limits:
          memory: 20M

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: paymentspass
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 100M
    command: >
      postgres
        -c shared_buffers=16MB
        -c work_mem=1MB
        -c maintenance_work_mem=8MB
        -c effective_cache_size=32MB
        -c max_connections=10
        -c log_min_messages=WARNING
