spring:
  application:
    name: rinhabackend2025
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DBSERVER:localhost}:5432/${DBNAME:payments}
    username: ${DBUSER:payments}
    password: ${DBPASS:paymentspass}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 3000
      idle-timeout: 10000
      max-lifetime: 30001
      keepalive-time: 30000
      validation-timeout: 2000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

server:
  error:
   include-exception: false
   include-stacktrace: never
   include-message: always
   include-binding-errors: never

logging:
  level:
    root: WARN
#    reactor:
#      netty:
#        http:
#          client: DEBUG
#    com:
#      andsantos:
#      service:
#        PagamentoService: DEBUG
#    org:
#      springframework:
#        web:
#          reactive:
#            function:
#              client: DEBUG

env:
  NATS_SERVER: ${NATS_SERVER:nats://localhost:4222}
  API_PAYMENT_DEFAULT: ${API_PAYMENT_DEFAULT:http://localhost:8001/payments}
  API_PAYMENT_FALLBACK: ${API_PAYMENT_FALLBACK:http://localhost:8002/payments}
  NOME_FILA: ${NOME_FILA:topico.pagamento}

